package com.example.fitfusion.ui.screens

enum class Screens {
    LoginScreen,
    SignUpScreen,
    HomeScreen,
    TrackingScreen,
    ProfileScreen,
    SettingsScreen,
    PostDetailScreen,
    WorkoutSummaryScreen,
    AddFoodScreen,
    AddWorkoutScreen,
    AccountScreen,
    PrivacyScreen,
    DataStorageScreen,
    HelpSupportScreen,
    ExerciseDetailScreen,
    CreateExerciseScreen,
    WeeklyLogScreen,
    CreateRecipeScreen,
    PlannerScreen,
    CreateRoutineScreen,
    CreateWeeklyPlanScreen,
}