package com.example.fitfusion.ui.screens

enum class Screens {
    LoginScreen,
    SignUpScreen,
    OnboardingScreen,
    HomeScreen,
    TrackingScreen,
    ProfileScreen,
    SettingsScreen,
    PostDetailScreen,
    AddFoodScreen,
    AddWorkoutScreen,
    ActiveWorkoutScreen,
    WorkoutFinishScreen,
    WorkoutPostScreen,
    AccountScreen,
    PrivacyScreen,
    DataStorageScreen,
    HelpSupportScreen,
    ExerciseDetailScreen,
    CreateExerciseScreen,
    WeeklyLogScreen,
    CreateRecipeScreen,
    PlannerScreen,
    CreateRoutineScreen,
    CreateWeeklyPlanScreen,
    WorkoutScreen,
    UserSearchScreen,
    UserScreen,
}